name: All Specs
on:
  - push
  - pull_request
  - workflow_dispatch

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-22.04
    env:
      RAILS_MASTER_KEY: ${{ secrets.RAILS_MASTER_KEY }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: '13.14.0' 
      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true # Automatically runs 'bundle install' and caches gems
      - run: npm install -g yarn@1.19.1 # Your Yarn version
      - run: bundle install
      - run: yarn install
      - run: bundle exec rake db:setup
      - run: bundle exec rake db:test:prepare
      - run: bundle exec rspec
      - run: bundle exec cucumber
